server:
  port: 8085
  servlet:
    context-path: /capgbanking
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mySBdb
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    
    
    

    